from django.urls import path
from  .views import *

urlpatterns = [
    path('', home),
    path('admin-login/', admin_login_api ),
    path('add-category/', add_category),
    path('categories/', list_categories),
    path('add-food-item/', add_food_item),
    path('foods/', list_foods),
    path('food-search/', food_search),
    path('random-foods/', random_foods),
    path('register/', register_user),
    path('login/', login_user),
    path('foods/<int:id>/', food_detail),
    path('cart/add/', add_to_cart),
    path('cart/<int:user_id>/', get_cart_items),
    path('cart/update_quantity/', update_cart_quantity),
    path('cart/delete/<int:order_id>/', delete_cart_item),
    path('place_order/', place_order),
    path('orders/<int:user_id>/', user_orders),
    path('orders/by_order_number/<str:order_number>/', order_by_order_number),
    path('order_address/<str:order_number>/', get_order_address),
    path('invoice/<str:order_number>/', get_invoice),
    path('user/<int:user_id>/', get_user_profile),
    path('user_update/<int:user_id>/', update_user_profile),
    path('change_password/<int:user_id>/', change_password),
    path('orders-not-confirmed/', orders_not_confirmed),   
    path('orders-confirmed/', orders_confirmed),
    path('food_being_prepared/', food_being_prepared),
    path('foodpickup/', food_pickup),
    path('orders-delivered/', food_delivered),
    path('order-cancelled/', order_cancelled),
    path('all-foods/', all_orders),
    path('order-between-dates/', order_between_dates),
    path('view-order-detail/<str:order_number>/', view_order_detail),
    path('update-order-status/', update_order_status),
    path('search-orders/', search_orders),
    path('category/<str:id>/', category_update),
    path('delete-food/<str:id>/', delete_food),
    path('edit-food/<str:id>/', edit_food),
    path('users/', list_users),
    path('delete-user/<int:id>/', delete_user),
    path('dashboard_metrics/', dashboard_metrics),
    path('monthly_sales_summary/', monthly_sales_summary),
    path('top_selling_foods/', top_selling_foods),
    path('weekly_sales_summary/', weekly_sales_summary),
    path('weekly_user_registrations/', weekly_user_registrations),
    path('wishlist/add/', add_to_wishlist),
    path('wishlist/remove/', remove_from_wishlist),
    path('wishlist/<int:user_id>/', get_wishlist),
    path('track_order/<str:order_number>/', track_order),
    path('cancel_order/<str:order_number>/', cancel_order),
    path('reviews/add/<str:food_id>/', add_review),
    path('reviews/<str:food_id>/', food_reviews),
    path('review_edit/<str:id>/', review_detail),
    path('food_rating_summary/<str:id>/', food_rating_summary),
    path('all-reviews/', all_reviews),
    path('delete_review/<str:id>/', delete_review),
]
