# Generated by Django 6.0.2 on 2026-02-26 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0004_orderaddress_ordertracking_paymentdetail_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderaddress',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='created_at',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='address_line_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='state',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderaddress',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='foodordering.order'),
        ),
    ]
