# Generated by Django 6.0.2 on 2026-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0005_remove_orderaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderaddress',
            name='address_line_1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
