# Generated by Django 6.0.2 on 2026-02-26 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0006_alter_orderaddress_address_line_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='foodordering.user'),
            preserve_default=False,
        ),
    ]
