# Generated by Django 6.0.2 on 2026-02-27 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0007_paymentdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
